module.exports = [
    "The world's least convincing disguise",
    "Trying to look innocent",
    "My last two brain cells",
    "When the tutorial ends",
    "Accidentally becoming the villain",
    "The final boss of customer service",
    "Trying to act natural",
    "If raccoons ruled the world",
    "How I'd survive exactly five minutes in a horror movie",
    "The FBI agent reading my search history",
    "The most suspicious thing to do in public",
    "How I'd lose the Hunger Games",
    "When someone says 'hear me out'",
    "Trying to explain this to my future self",
    "My emotional support object",
    "The most dramatic way to leave a room",
    "The first person to try milk",
    "If pigeons paid taxes",
    "The group project after one person leaves",
    "Trying to bluff with absolutely no information",
    "The worst possible superhero",
    "The most cursed family reunion",
    "How I'd react to finding Bigfoot",
    "When the boss has a second phase",
    "Trying to convince the police this makes sense",
    "The council deciding my fate",
    "Me after one minor inconvenience",
    "The first thing I'd do with unlimited power",
    "The least intimidating villain speech",
    "Trying to sneak while carrying pots and pans",
    "How my ancestors watch me",
    "The NPC that's secretly the main character",
    "The world's most dramatic apology",
    "If IKEA was a dungeon",
    "Trying to win an argument against a toddler",
    "The most overqualified goblin",
    "The dragon's accountant",
    "The first day working at Area 51",
    "How I'd accidentally start a revolution",
    "Trying to gaslight the GPS",
    "The weirdest Olympic event",
    "The employee of the month in Hell",
    "How I'd react to a ghost asking for directions",
    "The duck that has had enough",
    "Trying to impress a wizard",
    "The worst roommate imaginable",
    "If gravity stopped for five seconds",
    "The villain making a good point",
    "When the side quest becomes the main quest",
    "My brain during an awkward silence",

    "The first human to see fire",
    "The last person I'd trust with a time machine",
    "How I'd fail a stealth mission",
    "Trying to explain memes to Shakespeare",
    "If sharks could walk",
    "The raccoon leading a business meeting",
    "The skeleton in my closet finally escaping",
    "Trying to look busy at work",
    "The world's most inconvenient superpower",
    "The goose that knows your address",
    "When your lie requires another lie",
    "Trying to hide from responsibilities",
    "The medieval equivalent of tech support",
    "The pirate HR department",
    "How I'd react if the moon blinked",
    "The wizard forgetting the spell",
    "Trying to outsmart a Roomba",
    "If dinosaurs came back tomorrow",
    "The final slice of pizza",
    "The oldest vampire trying modern technology",
    "Trying to blend in with humans",
    "When the AI becomes self-aware",
    "The least qualified lifeguard",
    "If aliens judged us by social media",
    "Trying to survive Black Friday",
    "The squirrel planning world domination",
    "When your pet knows too much",
    "The goblin applying for a mortgage",
    "Trying to look confident",
    "The first zombie at customer service",
    "How I'd react to free food",
    "When the coffee finally kicks in",
    "Trying to remember why I walked into this room",
    "The most dramatic grocery shopping trip",
    "When the Wi-Fi comes back",
    "Trying to parallel park under pressure",
    "The first person to eat a mushroom",
    "The world's worst magician",
    "Trying to avoid eye contact",
    "When autocorrect betrays you",
    "The office microwave after fish",
    "The most cursed cooking show",
    "When someone steals my fries",
    "Trying to look awake",
    "The world's slowest chase scene",
    "How I'd react to winning the lottery",
    "When someone says 'it's just a quick meeting'",
    "The cat secretly running the house",
    "Trying to survive Monday",
    "The world's most dramatic sneeze",

    "When the teacher says 'pick a partner'",
    "Trying to remember a password",
    "The first person to invent taxes",
    "The villain's LinkedIn profile",
    "How I'd escape prison",
    "The raccoon stealing my identity",
    "Trying to explain my hobbies",
    "The duck in charge of airport security",
    "When the food arrives",
    "Trying to leave a party without saying goodbye",
    "The world's most awkward handshake",
    "How I'd react if my fridge talked",
    "The goblin discovering capitalism",
    "Trying to hide after sending the wrong message",
    "When someone starts clapping on a plane",
    "The first person to trust a cat",
    "The villain discovering friendship",
    "Trying to look cool after tripping",
    "When the waiter asks how the food is",
    "The world's most dramatic eye roll",
    "Trying to open childproof packaging",
    "The goose becoming president",
    "When someone says 'don't panic'",
    "Trying to explain the internet to a knight",
    "The medieval influencer",
    "The wizard with stage fright",
    "Trying to get one sock to match",
    "The office plant watching everything",
    "How I'd react to a UFO landing",
    "The worst detective",
    "Trying to act like I belong",
    "The first robot to get tired",
    "When someone spoils the movie",
    "The raccoon that pays taxes",
    "Trying to stay awake in a meeting",
    "The dragon trying yoga",
    "When someone replies 'k'",
    "Trying to ignore an embarrassing memory",
    "The villain reading the reviews",
    "The goose opening a bank account",
    "Trying to explain why I'm late",
    "The world's loudest secret",
    "The cat pretending not to care",
    "When someone says 'calm down'",
    "Trying to carry every grocery bag in one trip",
    "The pirate using GPS",
    "The wizard learning Excel",
    "Trying to fix it without instructions",
    "The first alien tourist",
    "When someone asks what I'm thinking",

    "The NPC that knows too much",
    "Trying to survive family game night",
    "The world's most dramatic text message",
    "How I'd react to immortality",
    "The goblin discovering coffee",
    "Trying to explain this to customer support",
    "The duck winning an Oscar",
    "When my alarm goes off",
    "Trying to make a good first impression",
    "The medieval IT department",
    "The villain getting stuck in traffic",
    "Trying to fold a fitted sheet",
    "The dragon attending therapy",
    "When the plot twist finally hits",
    "Trying to act surprised",
    "The raccoon applying for a passport",
    "When someone asks if I'm okay",
    "Trying to speedrun adulthood",
    "The wizard ordering fast food",
    "The goose becoming a lawyer",
    "Trying to explain why this is funny",
    "When someone says 'one more episode'",
    "The world's smallest violin",
    "Trying to survive without caffeine",
    "The pirate filing paperwork",
    "The dragon at IKEA",
    "Trying to impress my past self",
    "The cat judging everyone",
    "When the elevator gets awkwardly quiet",
    "Trying to avoid spoilers",
    "The villain's vacation",
    "The raccoon buying cryptocurrency",
    "Trying to explain my life choices",
    "The duck solving world hunger",
    "When someone says 'it's not that bad'",
    "Trying to survive a family group chat",
    "The medieval customer review",
    "The wizard accidentally summoning HR",
    "Trying to keep a straight face",
    "The dragon learning to knit",
    "When someone says 'this will only take five minutes'",
    "Trying to win with pure confidence",
    "The goose starting a podcast",
    "The pirate attending a job interview",
    "Trying to avoid responsibilities for one more day",
    "The villain realizing they're in the wrong movie",
    "The raccoon getting promoted",
    "Trying to explain this without context",
    "The duck becoming self-aware",
    "How history books will describe me",
    "The most chaotic timeline",
    "Trying to look like I have a plan",
    "The ending nobody saw coming"
];
